#!/bin/sh
#****************************************************************#
# ScriptName: checkyaochiservice.sh
# Author: liuhb@dtdream.com
# Create Date: 2015-11-11 13:29
# Modify Author: $SHTERM_REAL_USER@alibaba-inc.com
# Modify Date: 2015-11-14 21:31
# Function: used for check all yaochi serivce except dubbo  zookpeer    metaq
#***************************************************************#
workdir=`pwd`
times=`cat $workdir/servicelist |wc -l`
if  [ -z $1 ]
then 
       echo "this shell must choose {checkyc|rs}";
elif [ $1 = "checkyc" ]
then
	for ((i=1; i<=$times; i++));
	do
	    checkingservice=`cat $workdir/servicelist |awk "NR==$i"`;
	    echo checking $checkingservice;
	    /mnt/shuguang/cmdbClient.py host /yaochi/$checkingservice=host >iplist;
	    pssh -P -h iplist "curl --connect-timeout 100 -v  http://localhost:18080/$checkingservice/check_health" >log.log;
	    if grep -qc "ok" log.log
	    then
	        echo "$checkingservice is ok"
	    else
	        echo "check $checkingservice failed"
	    fi;
	done;
elif [ $1 = "rs" ]
then
	echo "this restartingservice is developing please wait";i
    if [ $2 = "console" ]
    then 
        echo "console"
    else
        echo "plsease the level {console|L1|L2}"
    fi
fi
